### ISSUE TITLE
Importer not working on Make Events Not War staging

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-importer#55] opened 2019-06-13 18:14 UTC
**Summary**
I'm trying out the importer here with my staff account: https://lorenzo1072.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_importer

...using this CSV file: https://cl.ly/f27496d89a94/download/Testing%252520Attendee%252520Importer%252520-%252520Sheet1.csv

The file above is generated from this Google Sheet: https://docs.google.com/spreadsheets/d/1F6ZT-lOT36oYqxZbywIo5Cy8toRDk4CqaQD8szk9LrA/edit#gid=0

I can get to the end and click the import button. On clicking, I'm taken back to the events overview screen. I don't see any errors on the screen and Rapid 7 logs is empty:

https://eu.ops.insight.rapid7.com/op/3C2621E689F216EF69EE#/search?logs=%5B%2227231556-ebec-48d8-b8ef-d51bf31a7761%22%2C%2231596140-8113-4bbd-be59-b0aee1fc821f%22%5D&query=where(NOT%20Hook%3A)&range=Last%201%20Hour

I also tried other events and also importing just the personal information plus the payment amount.

**Steps to reproduce**
Same as above

**Reported or seen on**
https://lorenzo1072.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_importer

**Other notes**
This is a newer site on staging. I'll check a different site to see if its working.

**Comment by lorenzocaum** [comment] 2019-06-13 18:20
I checked this site and the data isn't imported:

https://lorenzo313chrome.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_importer

Any ideas on what might be happening?

**Comment by mnelson4** [comment] 2019-06-13 18:47
nope. Anybody else? jk, I'll take a gander, thanks for making the site available for inspection...

**Comment by mnelson4** [comment] 2019-06-13 19:18
It's something specific to your setup, because I can import using that file fine on my machine so long as the WP user integration add-on isn't on (see https://github.com/eventespresso/eea-importer/issues/53), so it may be another add-ons that is doesn't play nicely with the importer...

**Comment by lorenzocaum** [comment] 2019-06-13 19:51
Hey Mike, thanks for looking. I'll activate the same add-ons on a local site to see if I can pinpoint the one that might be causing an issue on Make Events Not War.

**Comment by lorenzocaum** [comment] 2019-06-13 20:39
I added the same add-ons to my testing site and I was able to run an import. I noticed that it does a sort of redirect and  ends up here for espresso_batch:

https://ypenzo12.wpengine.com/wp-admin/?page=espresso_batch&batch=job&label=ApplyingOffset&job_handler=EventEspresso%5CAttendeeImporter%5Cdomain%5Cservices%5Cbatch%5CJobHandlers%5CAttendeeImporterBatchJob&return_url=https%3A%2F%2Fypenzo12.wpengine.com%2Fwp-admin%2Fadmin.php%3Fpage%3Despresso_importer%26action%3Dimport%26type%3Dcsv-attendee%26import_nonce%3Df480ea3e93%26ee-form-step%3Dcomplete&action=default&default_nonce=9e39a664c4

On my testing site on Make Events Not War, it doesn't make it that far and ends up at the events overview screen.

**Comment by lorenzocaum** [comment] 2019-06-13 21:04
It starts here:

https://lorenzo1072.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_importer&action=import&type=csv-attendee&import_nonce=74919a94ef&ee-form-step=verify

...which then redirects here:

https://lorenzo1072.makeeventsnotwar.com/wp-admin/?page=espresso_batch&batch=job&label=ApplyingOffset&job_handler=EventEspresso%5CAttendeeImporter%5Cdomain%5Cservices%5Cbatch%5CJobHandlers%5CAttendeeImporterBatchJob&return_url=https%3A%2F%2Florenzo1072.makeeventsnotwar.com%2Fwp-admin%2Fadmin.php%3Fpage%3Despresso_importer%26action%3Dimport%26type%3Dcsv-attendee%26import_nonce%3D74919a94ef%26ee_return%3Dimport%26ee-form-step%3Dcomplete&action=default&default_nonce=ff23a0c722&return=import

...which then redirects here: https://lorenzo1072.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_events

I wonder if something like this is happening: https://github.com/eventespresso/eventsmart.com-website/issues/177

**Comment by lorenzocaum** [comment] 2019-06-13 21:09
Hey Seth, the Attendee Importer isn't working on Make Events Not War staging. I think it may be related to a redirect but I'm not sure: https://github.com/eventespresso/eea-importer/issues/55#issuecomment-501878396

Could someone investigate this further next week?

**Comment by mnelson4** [comment] 2019-06-13 21:28
Ok thanks for the update Lorenzo. Ya the user is never arriving at the batch processing page, so the users aren't ever imported. Offhand, I have no idea why its sending you to the event list page.
It  doesn't seem to be the exact same issue as https://github.com/eventespresso/eventsmart.com-website/issues/177 (no double question marks) but it must be something like that.

**Comment by mnelson4** [comment] 2019-06-13 23:08
great news everyone! I'm reproducing this on my local copy of MENW. Let the debugging begin! :racehorse:

**Comment by mnelson4** [comment] 2019-06-13 23:31
Hmmm, it appaers `EED_Batch::enqueue_scripts()`, which is what handles the batch job, isn't getting called. Some other code is doing the redirect before it has a chance...

**Comment by mnelson4** [comment] 2019-06-13 23:40
aha, I see `\EE_Whitelabeler_Hooks::redirect_dashboard_load()` is doing the redirect... and the reason is because I'm sending the user to `wp-admin/?...` whereas I should send them to `wp-admin/admin.php?...`
Patch forthcoming...

**Comment by mnelson4** [comment] 2019-06-19 16:28
Once the attendee importer is updated on MENW, this should be fixed.

**Comment by joshfeck** [comment] 2019-06-24 20:26
closing this since #57 was merged

**Closed by joshfeck** 2019-06-24 20:26 UTC
Labels: type:bug 🐞
